### ISSUE TITLE
Core Refactor

### ISSUE THREAD

**Issue by jwerle** [sphia/sphia#52]
- [ ] `sphia_get` refactor (#54)
- [ ] `sphia_set` refactor (#55)
- [ ] `sphia_rm` refactor (#56)

**Comment by stephenmathieson** [comment]
I assume we're just going to use libsphia once it's complete?

**Comment by jwerle** [comment]
yep!
